# Generated by Django 2.1.2 on 2018-10-31 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='CONTENT')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE')),
                ('status', models.CharField(default='Y', max_length=1, verbose_name='STATUS')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
